### ISSUE TITLE
Feature request - toggle showing Ghost actionbars

### ISSUE THREAD

**Issue by FrostShock** [diff3/Ghost#1]
Hello, I would like to place the following feature request:

When you push the keybind for Ghost, show the actionbars, and then when you push the keybind again, stop showing it. [Ringmenu](https://github.com/jsb/RingMenu/releases/tag/v1.0.2) works like this, and it's more convenient.

Instead of showing it only while the keybind is pressed, as it works now

**Comment by diff3** [comment]
I'm not playing WoW anymore, feel free to add this yourself
